import { StyleSheet, Dimensions } from "react-native";

const { width: W } = Dimensions.get("window");

export const COLORS = {
  bg: "#F8F9FF",
  heroCard: "#EAE8FF",
  orbOuter: "rgba(255,255,255,0.35)",
  orbMid: "rgba(255,255,255,0.55)",
  orbInner: "#FFFFFF",
  title: "#1D3B65",
  muted: "#6B7280",
  primary: "#22BEC8",
  orange: "#F97316",
  dark: "#111827",
  inputBg: "#F3F4F6",
  pillBg: "#F3F4F6",
  sendBtn: "#1D3B65",
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerMenuBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: { fontSize: 17, fontWeight: "800", color: "#FFFFFF" },

  scroll: { paddingHorizontal: 16, paddingBottom: 60, marginTop: 8 },

  // ── Hero card ──────────────────────────────────────────────────────────────
  heroCard: {
    borderRadius: 28,
    overflow: "hidden",
    marginBottom: 14,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 20,
    alignItems: "center",
    shadowColor: "#7C6FCD",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  star: {
    position: "absolute",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  heroTopRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  avatarStack: { flexDirection: "row", alignItems: "center" },
  childAvatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    overflow: "visible",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  childAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  childAvatarText: { fontSize: 15, fontWeight: "800", color: "#FFFFFF" },
  liveDot: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#22C55E",
    borderWidth: 2.5,
    borderColor: "#FFFFFF",
  },
  filterBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Orb (old SVG orb + teacher photo in center) ────────────────────────────
  orbContainer: {
    width: 170,
    height: 170,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 6,
  },
  orbPulseGlow: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(255,255,255,0.9)",
    shadowColor: "#FFFFFF",
    shadowOpacity: 1,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 0 },
  },
  orbTeacher: {
    position: "absolute",
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 4,
    borderColor: "#FFFFFF",
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    shadowColor: "#7C6FCD",
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  orbTeacherImg: {
    width: "100%",
    height: "100%",
    borderRadius: 48,
  },

  greetingBubble: {
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.22)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 16,
    marginTop: 6,
  },
  heroGreeting: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
  },

  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  actionBtn: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.7)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  micBtn: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: COLORS.dark,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },

  // ── Prompts row ───────────────────────────────────────────────────────────
  promptsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  promptsLeft: { flexDirection: "row", alignItems: "center", gap: 5 },
  promptsText: { fontSize: 12.5, fontWeight: "700", color: COLORS.title },
  poweredText: { fontSize: 11.5, fontWeight: "600", color: COLORS.muted },

  // ── Input bar ─────────────────────────────────────────────────────────────
  inputBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
    gap: 10,
  },
  input: { flex: 1, fontSize: 14, color: COLORS.title, padding: 0 },
  sendBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: COLORS.sendBtn,
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Pills ─────────────────────────────────────────────────────────────────
  pillsScroll: { marginBottom: 20 },
  pillsRow: { flexDirection: "row", gap: 8, paddingRight: 4 },
  pillActive: {
    paddingHorizontal: 18,
    height: 36,
    borderRadius: 999,
    backgroundColor: COLORS.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  pillActiveText: { fontSize: 13, fontWeight: "700", color: "#FFFFFF" },
  pill: {
    paddingHorizontal: 16,
    height: 36,
    borderRadius: 999,
    backgroundColor: COLORS.pillBg,
    alignItems: "center",
    justifyContent: "center",
  },
  pillText: { fontSize: 13, fontWeight: "600", color: COLORS.title },

  // ── Roadmap ───────────────────────────────────────────────────────────────
  roadmapSection: {},
  roadmapHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  roadmapTitle: { fontSize: 18, fontWeight: "900", color: COLORS.title },
  roadmapTabs: { flexDirection: "row", gap: 4 },
  roadmapTab: { paddingHorizontal: 8, paddingVertical: 4 },
  roadmapTabActive: { borderBottomWidth: 2, borderBottomColor: COLORS.title },
  roadmapTabText: { fontSize: 12, fontWeight: "600", color: COLORS.muted },
  roadmapTabTextActive: { color: COLORS.title, fontWeight: "800" },

  ganttContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  ganttRow: {
    flexDirection: "row",
    alignItems: "center",
    height: 48,
    marginBottom: 4,
  },
  ganttLabelCol: {
    width: 140,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ganttDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1D3B65",
  },
  ganttLabel: { fontSize: 12, fontWeight: "700", color: COLORS.title, flex: 1 },
  ganttBarArea: {
    flex: 1,
    height: 28,
    position: "relative",
  },
  ganttBar: {
    position: "absolute",
    height: 28,
    borderRadius: 8,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  progressBadge: {
    position: "absolute",
    top: -10,
    left: 6,
    backgroundColor: COLORS.dark,
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  progressText: { fontSize: 10, fontWeight: "800", color: "#FFFFFF" },
  ganttAvatar: {
    position: "absolute",
    top: -6,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    overflow: "hidden",
  },

  // ── Timeline ──────────────────────────────────────────────────────────────
  timeline: {
    flexDirection: "row",
    marginTop: 8,
    paddingLeft: 140,
  },
  timelineDay: { flex: 1, alignItems: "center", position: "relative" },
  timelineDayText: { fontSize: 11, fontWeight: "600", color: COLORS.muted },
  timelineDayActive: { color: COLORS.title, fontWeight: "800" },
  timelineLine: {
    position: "absolute",
    top: -172,
    width: 2,
    height: 172,
    backgroundColor: COLORS.orange,
    opacity: 0.4,
    borderRadius: 1,
  },

  // ── Meeting details card ──────────────────────────────────────────────────
  detailSection: { marginTop: 20 },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  detailTitleDot: { width: 10, height: 10, borderRadius: 5 },
  detailTitle: { fontSize: 18, fontWeight: "900", color: COLORS.title },

  detailCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },

  cardSubjectPillRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  cardSubjectPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  cardSubjectPillText: { fontSize: 12, fontWeight: "700" },

  sessionTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  groupPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  groupPillText: { fontSize: 12, fontWeight: "700", color: COLORS.title },
  sessionFreq: { fontSize: 12, fontWeight: "600", color: COLORS.muted },

  dayPillsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  dayPill: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
  },
  dayPillActive: { backgroundColor: COLORS.dark, borderColor: COLORS.dark },
  dayPillOff: { backgroundColor: "#F3F4F6", borderColor: "#E5E7EB" },
  dayPillText: { fontSize: 13, fontWeight: "800" },
  dayPillTextActive: { color: "#FFFFFF" },
  dayPillTextOff: { color: "#9CA3AF" },

  reserveRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  reserveAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    backgroundColor: "#F3F4F6",
  },
  reserveText: { fontSize: 12.5, fontWeight: "600", color: COLORS.muted },

  placesBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F3F4F6",
    overflow: "hidden",
    marginBottom: 6,
  },
  placesFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: COLORS.orange,
  },
  placesCaption: {
    fontSize: 11.5,
    fontWeight: "600",
    color: COLORS.muted,
    marginBottom: 14,
  },

  detailPriceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  detailPriceValue: { fontSize: 22, fontWeight: "900", color: COLORS.title },
  detailPriceUnit: { fontSize: 13, fontWeight: "600", color: COLORS.muted },
});
