import { StyleSheet, Dimensions } from "react-native";

const { width: W } = Dimensions.get("window");

export const COLORS = {
  bg: "#F8F9FF",
  heroCard: "#EAE8FF",
  orbOuter: "rgba(255,255,255,0.35)",
  orbMid: "rgba(255,255,255,0.55)",
  orbInner: "#FFFFFF",
  title: "#1D3B65",
  muted: "#6B7280",
  primary: "#22BEC8",
  orange: "#F97316",
  dark: "#111827",
  inputBg: "#F3F4F6",
  pillBg: "#F3F4F6",
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerMenuBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: { fontSize: 17, fontWeight: "800", color: "#FFFFFF" },

  scroll: { paddingHorizontal: 16, paddingBottom: 60, marginTop: 8 },

  // ── Hero card ──────────────────────────────────────────────────────────────
  heroCard: {
    borderRadius: 28,
    overflow: "hidden",
    marginBottom: 14,
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 10,
    alignItems: "center",
    shadowColor: "#4781dd",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  star: {
    position: "absolute",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  heroTopRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  heroTopActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  askBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  askBtnText: { fontSize: 12, fontWeight: "700", color: "#FFFFFF" },
  avatarStack: { flexDirection: "row", alignItems: "center" },
  childAvatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    overflow: "visible",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  childAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  childAvatarText: { fontSize: 15, fontWeight: "800", color: "#FFFFFF" },
  liveDot: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#22C55E",
    borderWidth: 2.5,
    borderColor: "#FFFFFF",
  },
  filterBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Orb (old SVG orb + teacher photo in center) ────────────────────────────
  orbContainer: {
    width: 130,
    height: 130,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 2,
  },
  orbPulseGlow: {
    position: "absolute",
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: "rgba(255,255,255,0.9)",
    shadowColor: "#FFFFFF",
    shadowOpacity: 1,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
  },
  orbTeacher: {
    position: "absolute",
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 3,
    borderColor: "#FFFFFF",
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    shadowColor: "#7C6FCD",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  orbTeacherImg: {
    width: "100%",
    height: "100%",
    borderRadius: 35,
  },

  greetingBubble: {
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.22)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 12,
    marginTop: 2,
  },
  heroGreeting: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
  },

  joinBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    alignSelf: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 9,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  joinBtnIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.dark,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 2,
  },
  joinBtnText: { fontSize: 14, fontWeight: "800", color: COLORS.dark },

  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  actionBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.7)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  micBtn: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: COLORS.dark,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },

  // ── Ask-admin dropdown ────────────────────────────────────────────────────
  askDropdown: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingVertical: 4,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  askHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  askHeaderTitle: { fontSize: 13.5, fontWeight: "800", color: COLORS.title },
  askItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  askItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  askItemText: {
    fontSize: 13.5,
    fontWeight: "600",
    color: COLORS.title,
    flex: 1,
  },
  askItemSelected: { backgroundColor: "#F0FDFA" },
  askItemTextSelected: { color: COLORS.title, fontWeight: "800" },
  askFooter: {
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  askSendBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: COLORS.dark,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 9,
  },
  askSendBtnDisabled: { opacity: 0.4 },
  askSendBtnText: { fontSize: 13, fontWeight: "800", color: "#FFFFFF" },

  sentCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#ECFDF5",
    borderWidth: 1,
    borderColor: "#D1FAE5",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 12,
  },
  sentIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#22C55E",
    alignItems: "center",
    justifyContent: "center",
  },
  sentTextWrap: { flex: 1 },
  sentTitle: { fontSize: 13, fontWeight: "800", color: COLORS.dark },
  sentSub: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.muted,
    marginTop: 1,
  },

  // ── Pills ─────────────────────────────────────────────────────────────────
  pillsScroll: { marginBottom: 20 },
  pillsRow: { flexDirection: "row", gap: 8, paddingRight: 4 },
  pillActive: {
    paddingHorizontal: 18,
    height: 36,
    borderRadius: 999,
    backgroundColor: COLORS.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  pillActiveText: { fontSize: 13, fontWeight: "700", color: "#FFFFFF" },
  pill: {
    paddingHorizontal: 16,
    height: 36,
    borderRadius: 999,
    backgroundColor: COLORS.pillBg,
    alignItems: "center",
    justifyContent: "center",
  },
  pillText: { fontSize: 13, fontWeight: "600", color: COLORS.title },

  // ── Roadmap ───────────────────────────────────────────────────────────────
  roadmapSection: { marginTop: 8 },
  roadmapHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  roadmapTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  roadmapIcon: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  roadmapTitle: { fontSize: 18, fontWeight: "900", color: COLORS.title },
  roadmapTabs: {
    flexDirection: "row",
    backgroundColor: "#F3F4F6",
    borderRadius: 999,
    padding: 3,
    gap: 2,
  },
  roadmapTab: {
    paddingHorizontal: 10,
    height: 26,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  roadmapTabActive: { backgroundColor: COLORS.dark },
  roadmapTabText: { fontSize: 11.5, fontWeight: "700", color: COLORS.muted },
  roadmapTabTextActive: { color: "#FFFFFF", fontWeight: "800" },

  // ── Calendar card (weekly — teacher + days + material) ───────────────────
  calendarCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  calTeacherRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  calTeacherAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#22BEC8",
    padding: 1,
    backgroundColor: "#FFFFFF",
  },
  calTeacherImg: { width: "100%", height: "100%", borderRadius: 22 },
  calTeacherInfo: { flex: 1 },
  calTeacherName: { fontSize: 15, fontWeight: "800", color: COLORS.title },
  calTeacherSub: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.muted,
    marginTop: 2,
  },
  calNextPill: {
    backgroundColor: "#F3F4F6",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  calNextPillText: { fontSize: 11, fontWeight: "700", color: COLORS.title },

  calWeekGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  calDayCol: { alignItems: "center", flex: 1, gap: 6 },
  calDayLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.muted,
    textTransform: "uppercase",
  },
  calDateWrap: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F4F6",
  },
  calDateToday: {
    borderWidth: 2,
    borderColor: "#22BEC8",
  },
  calDateText: { fontSize: 13, fontWeight: "800", color: COLORS.title },
  calDateTextActive: { color: "#FFFFFF" },
  calDateTextToday: { color: "#FFFFFF" },
  calMatChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 4,
    maxWidth: 54,
  },
  calMatDot: { width: 5, height: 5, borderRadius: 2.5 },
  calMatText: { fontSize: 8.5, fontWeight: "800" },
  calMatEmpty: { height: 18 },

  calFooter: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingTop: 12,
  },
  calStat: { flex: 1, alignItems: "center", gap: 2 },
  calStatValue: { fontSize: 16, fontWeight: "900", color: COLORS.title },
  calStatLabel: { fontSize: 11, fontWeight: "600", color: COLORS.muted },
  calDivider: { width: 1, height: 28, backgroundColor: "#F3F4F6" },

  // ── Meeting details card ──────────────────────────────────────────────────
  detailSection: { marginTop: 20 },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  detailTitleDot: { width: 10, height: 10, borderRadius: 5 },
  detailTitle: { fontSize: 18, fontWeight: "900", color: COLORS.title },

  detailCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },

  subjHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  subjTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  subjTitle: { fontSize: 18, fontWeight: "900", color: COLORS.title },
  subjSessionsPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  subjSessionsText: { fontSize: 11.5, fontWeight: "700" },

  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  metaText: { fontSize: 12, fontWeight: "600", color: COLORS.muted },
  metaDot: {
    width: 3.5,
    height: 3.5,
    borderRadius: 2,
    backgroundColor: "#D1D5DB",
  },

  dayPillsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  dayPill: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
  },
  dayPillActive: { backgroundColor: COLORS.dark, borderColor: COLORS.dark },
  dayPillOff: { backgroundColor: "#F3F4F6", borderColor: "#E5E7EB" },
  dayPillText: { fontSize: 13, fontWeight: "800" },
  dayPillTextActive: { color: "#FFFFFF" },
  dayPillTextOff: { color: "#9CA3AF" },

  reservePlacesRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  reserveRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  reserveAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    backgroundColor: "#F3F4F6",
  },
  reserveText: { fontSize: 12.5, fontWeight: "600", color: COLORS.muted },

  placesBlock: { alignItems: "flex-end", gap: 4 },
  placesBar: {
    width: 100,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#F3F4F6",
    overflow: "hidden",
  },
  placesFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: COLORS.orange,
  },
  placesCaption: {
    fontSize: 11.5,
    fontWeight: "700",
    color: COLORS.muted,
  },

  abonnementSection: {
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  periodToggle: {
    flexDirection: "row",
    backgroundColor: "#F3F4F6",
    borderRadius: 10,
    padding: 3,
  },
  periodBtn: {
    paddingHorizontal: 12,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  periodBtnActive: { backgroundColor: COLORS.dark },
  periodBtnText: { fontSize: 11.5, fontWeight: "700", color: COLORS.muted },
  periodBtnTextActive: { color: "#FFFFFF" },
  abonnementRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  abonnementStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  abonnementRemaining: {
    fontSize: 30,
    fontWeight: "900",
    color: COLORS.title,
  },
  abonnementRemainingLabel: {
    fontSize: 12.5,
    fontWeight: "700",
    color: COLORS.title,
  },
  abonnementPrice: {
    fontSize: 11.5,
    fontWeight: "600",
    color: COLORS.muted,
    marginTop: 1,
  },
});
