export const MEETING_DETAIL_UI = {
  defaultTitle:      "meetings.detail_default_title",
  defaultSubject:    "meetings.detail_default_subject",
  sessionsSuffix:    "meetings.sessions_suffix",
  teacherLabel:      "meetings.detail_teacher_label",
  teacherPrefix:     "meetings.teacher_prefix",
  verifiedTeacher:   "meetings.verified_teacher",
  yearsExperience:   "meetings.detail_years_experience",
  viewProfile:       "meetings.detail_view_profile",
  summaryLabel:      "meetings.detail_summary_label",
  onlineLabel:       "meetings.detail_online_label",
  privateLabel:      "meetings.private_label",
  scheduleLabel:     "meetings.detail_schedule_label",
  minutesSuffix:     "meetings.detail_minutes_suffix",
  nextSessionLabel:  "meetings.next_session",
  nextSessionDay:    "meetings.detail_next_session_day",
  aboutLabel:        "meetings.detail_about_label",
  descriptionLabel:  "meetings.detail_description_label",
  groupsLabel:       "meetings.detail_groups_label",
  upcomingLabel:     "meetings.detail_upcoming_label",
  reviewsLabel:      "meetings.detail_reviews_label",
  priceCurrency:     "common.currency_tnd",
  priceSuffix:       "meetings.month_suffix",
  bookNow:           "meetings.book_now",
  loading:           "common.loading",
  errorTitle:        "common.generic_error",
  retry:             "common.retry",
} as const;
