export const LIQUID = {
  barWidthRatio: 0.9,
  barHeight: 78,
  bottomSpacing: 22,
  borderRadius: 40,
  backdropBlur: 40,
  bg: "rgba(255,255,255,0.55)",
  border: "rgba(0,0,0,0.12)",
  highlight: "rgba(255,255,255,0.60)",
  shadow: "rgba(0,0,0,0.15)",
  cyanColor: "#22BEC8",
  inactiveOpacity: 0.6,
  activeIconScale: 1.2,
  pressScale: 0.96,
  spring: { damping: 18, stiffness: 180, mass: 0.9, overshootClamping: false, energyThreshold: 0.01 } as const,
  transitionMs: 380,
  tabCount: 4,
  tabs: [
    { name: "Settings", label: "Profil", icon: "person-outline", iconFocused: "person" },
    { name: "Home", label: "Accueil", icon: "home-outline", iconFocused: "home" },
    { name: "Books", label: "Livres", icon: "book-outline", iconFocused: "book" },
    { name: "LearnCalendar", label: "Écoles", icon: "school-outline", iconFocused: "school" },
  ] as const,
} as const;
