import { Dimensions, StyleSheet } from "react-native";

const { width: W } = Dimensions.get("window");

type ThemeColors = {
  bg?: string;
  text?: string;
  muted?: string;
  border?: string;
  primary?: string;
  card?: string;
  danger?: string;
  gold?: string;
} | undefined;

const GOLD = "#8B5CF6";
const CYAN = "#22BEC8";

const sh = {
  shadowColor: "#000",
  shadowOpacity: 0.08,
  shadowRadius: 14,
  shadowOffset: { width: 0, height: 6 },
  elevation: 5,
};

export function getPlansPalette(colors: ThemeColors, isDark: boolean) {
  return {
    bg: colors?.bg ?? (isDark ? "#07111D" : "#F3F7FF"),
    text: colors?.text ?? (isDark ? "#F8FAFC" : "#10213A"),
    muted: colors?.muted ?? (isDark ? "#94A3B8" : "#6E7A96"),
    border: colors?.border ?? (isDark ? "rgba(148,163,184,0.18)" : "#E5ECF6"),
    primary: colors?.primary ?? "#22BEC8",
    card: colors?.card ?? (isDark ? "#0D1726" : "#FFFFFF"),
    danger: colors?.danger ?? "#EF4444",
    white: "#FFFFFF",
    gold: GOLD,
    goldStrong: "#6D28D9",
    success: "#16A34A",
    surface: isDark ? "#0B1422" : "#F8FBFF",
    surfaceAlt: isDark ? "#0F1B2D" : "#EEF6FF",
    heroBand: isDark ? "#0E1A2E" : "#F5FAFF",
  };
}

export const plansStyles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { flexGrow: 1, paddingBottom: 30 },

  header: {
    paddingHorizontal: 16,
    paddingBottom: 24,
    overflow: "hidden",
  },
  headerGlowLeft: {
    position: "absolute",
    width: 210,
    height: 210,
    borderRadius: 999,
    top: -70,
    left: -60,
    backgroundColor: "rgba(34,190,200,0.16)",
  },
  headerGlowRight: {
    position: "absolute",
    width: 170,
    height: 170,
    borderRadius: 999,
    bottom: -45,
    right: -40,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  headerBackBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  logoText: { flexDirection: "row", alignItems: "baseline" },
  logoA: { fontSize: 20, fontWeight: "900", color: "#22BEC8" },
  logoB: { fontSize: 20, fontWeight: "900", color: "#FFFFFF" },
  logoDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#22BEC8",
    marginLeft: 3,
    marginBottom: 3,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#FFFFFF",
    textAlign: "center",
    writingDirection: "rtl",
  },
  headerSubtitle: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: "700",
    color: "rgba(255,255,255,0.82)",
    textAlign: "center",
    writingDirection: "rtl",
  },

  body: {
    paddingHorizontal: 16,
    paddingTop: 14,
    gap: 14,
  },

  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    paddingHorizontal: 24,
  },
  stateText: {
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    writingDirection: "rtl",
  },
  retryBtn: {
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 999,
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
    minWidth: 130,
    justifyContent: "center",
  },
  retryBtnText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
    writingDirection: "rtl",
  },

  emptyCard: {
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    alignItems: "center",
    ...sh,
  },
  emptyTitle: {
    marginTop: 12,
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    writingDirection: "rtl",
  },
  emptyText: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
    writingDirection: "rtl",
    lineHeight: 22,
  },

  planCard: {
    borderRadius: 24,
    borderWidth: 1.5,
    padding: 16,
    ...sh,
  },
  planHeaderRow: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  planHeaderTexts: {
    flex: 1,
    alignItems: "flex-end",
  },
  planTitle: {
    fontSize: 20,
    fontWeight: "900",
    textAlign: "right",
    writingDirection: "rtl",
  },
  planDescription: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: "600",
    textAlign: "right",
    writingDirection: "rtl",
    lineHeight: 22,
  },

  planBadges: {
    alignItems: "flex-start",
    gap: 8,
  },
  popularBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#F5A623",
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 6,
  },
  popularBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "900",
    writingDirection: "rtl",
  },
  typeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  typeBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    writingDirection: "rtl",
  },

  sectionLabel: {
    fontSize: 13,
    fontWeight: "900",
    textAlign: "right",
    writingDirection: "rtl",
    marginBottom: 10,
  },

  featuresBlock: {
    marginTop: 18,
  },
  featureRow: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 10,
  },
  featureIconWrap: {
    width: 24,
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 1,
  },
  featureTexts: {
    flex: 1,
    alignItems: "flex-end",
  },
  featureTitle: {
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
    writingDirection: "rtl",
  },
  featureDescription: {
    marginTop: 2,
    fontSize: 11.5,
    fontWeight: "600",
    textAlign: "right",
    writingDirection: "rtl",
    lineHeight: 18,
  },

  pricingsBlock: {
    marginTop: 18,
    gap: 10,
  },
  pricingCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 12,
  },
  pricingTopRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  pricingMonths: {
    fontSize: 15,
    fontWeight: "900",
    writingDirection: "rtl",
  },
  pricingTypeBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  pricingTypeBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    writingDirection: "rtl",
  },

  priceLine: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    gap: 12,
  },
  priceLineLabel: {
    flex: 1,
    fontSize: 12.5,
    fontWeight: "800",
    textAlign: "right",
    writingDirection: "rtl",
  },
  priceLineRight: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
  },
  oldPrice: {
    fontSize: 11,
    fontWeight: "700",
    textDecorationLine: "line-through",
  },
  newPrice: {
    fontSize: 15,
    fontWeight: "900",
  },
  noDiscountPrice: {
    fontSize: 15,
    fontWeight: "900",
  },
  discountBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "rgba(34,190,200,0.12)",
  },
  discountBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#22BEC8",
  },
  priceHint: {
    marginTop: 8,
    fontSize: 11.5,
    fontWeight: "700",
    textAlign: "left",
  },

  accessibleWrap: {
    marginTop: 18,
  },
  accessibleChipsRow: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 8,
  },
  accessibleChip: {
    maxWidth: W - 80,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
  },
  accessibleChipText: {
    fontSize: 11,
    fontWeight: "800",
    writingDirection: "rtl",
    textAlign: "right",
  },

  materialsRow: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 8,
  },
  materialChip: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
  },
  materialChipText: {
    fontSize: 12,
    fontWeight: "700",
    writingDirection: "rtl",
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },

  teacherRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1.5,
    padding: 12,
    gap: 10,
  },
  teacherRowLeft: {
    alignItems: "center",
    justifyContent: "center",
  },
  teacherRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  teacherRowRight: {
    flex: 1,
  },
  teacherRowInfo: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 10,
  },
  teacherAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(34,190,200,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  teacherRowText: {
    flex: 1,
  },
  teacherRowName: {
    fontSize: 14,
    fontWeight: "800",
    writingDirection: "rtl",
    textAlign: "right",
  },
  teacherRowMeta: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  teacherRowSubject: {
    fontSize: 11,
    fontWeight: "600",
    writingDirection: "rtl",
  },
  teacherRowRating: {
    fontSize: 11,
    fontWeight: "700",
  },
});

export function createPlansStyles(colors: ThemeColors, isDark: boolean, isRTL: boolean) {
  const palette = getPlansPalette(colors, isDark);

  const row = isRTL ? ("row-reverse" as const) : ("row" as const);
  const textEnd = isRTL ? ("right" as const) : ("left" as const);
  const alignEnd = isRTL ? ("flex-end" as const) : ("flex-start" as const);
  const dir = isRTL ? ("rtl" as const) : ("ltr" as const);

  return StyleSheet.create({
    container: { flex: 1 },

    scrollContent: { flexGrow: 1, paddingBottom: 300 },

    header: {
      paddingHorizontal: 16,
      paddingBottom: 26,
      overflow: "hidden",
    },
    headerGlowLeft: {
      position: "absolute",
      width: 240,
      height: 240,
      borderRadius: 999,
      top: -90,
      left: -80,
      backgroundColor: "rgba(34,190,200,0.20)",
    },
    headerGlowRight: {
      position: "absolute",
      width: 200,
      height: 200,
      borderRadius: 999,
      bottom: -70,
      right: -60,
      backgroundColor: "rgba(255,255,255,0.06)",
    },
    headerDotRing: {
      position: "absolute",
      width: 130,
      height: 130,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.10)",
      bottom: -40,
      left: isRTL ? -50 : undefined,
      right: isRTL ? undefined : -50,
    },
    headerTopRow: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 14,
    },
    headerBackBtn: {
      width: 40,
      height: 40,
      borderRadius: 14,
      backgroundColor: "rgba(255,255,255,0.14)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.24)",
      alignItems: "center",
      justifyContent: "center",
    },
    logoText: { flexDirection: row, alignItems: "baseline" },
    logoA: { fontSize: 21, fontWeight: "900", color: CYAN },
    logoB: { fontSize: 21, fontWeight: "900", color: "#FFFFFF" },
    logoDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: CYAN,
      marginStart: 3,
      marginBottom: 3,
    },
    headerTitleRow: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
    },
    headerTitle: {
      fontSize: 25,
      fontWeight: "900",
      color: "#FFFFFF",
      textAlign: "center",
      writingDirection: dir,
      flex: 1,
    },
    headerSubtitle: {
      marginTop: 7,
      fontSize: 12.5,
      fontWeight: "700",
      color: "rgba(255,255,255,0.82)",
      textAlign: "center",
      writingDirection: dir,
      lineHeight: 20,
      paddingHorizontal: 8,
    },

    body: {
      paddingHorizontal: 16,
      paddingTop: 14,
      gap: 14,
    },

    centerState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 14,
      paddingHorizontal: 24,
    },
    stateText: {
      fontSize: 14,
      fontWeight: "700",
      textAlign: "center",
      writingDirection: dir,
    },
    retryBtn: {
      paddingHorizontal: 22,
      paddingVertical: 12,
      borderRadius: 999,
      flexDirection: row,
      alignItems: "center",
      gap: 8,
      minWidth: 130,
      justifyContent: "center",
    },
    retryBtnText: {
      fontSize: 14,
      fontWeight: "800",
      color: "#FFFFFF",
      writingDirection: dir,
    },

    emptyCard: {
      borderRadius: 22,
      padding: 20,
      borderWidth: 1,
      alignItems: "center",
      ...sh,
    },
    emptyTitle: {
      marginTop: 12,
      fontSize: 18,
      fontWeight: "900",
      textAlign: "center",
      writingDirection: dir,
    },
    emptyText: {
      marginTop: 6,
      fontSize: 13,
      fontWeight: "600",
      textAlign: "center",
      writingDirection: dir,
      lineHeight: 22,
    },

    periodWrap: {
      flexDirection: row,
      borderRadius: 999,
      padding: 4,
      borderWidth: 1,
      gap: 2,
    },
    periodBtn: {
      flex: 1,
      flexDirection: row,
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      borderRadius: 999,
      paddingVertical: 10,
      paddingHorizontal: 8,
    },
    periodActiveBg: {
      position: "absolute",
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      borderRadius: 999,
    },
    periodLabel: {
      fontSize: 12.5,
      fontWeight: "900",
      writingDirection: dir,
    },
    periodLabelActive: {
      color: "#FFFFFF",
    },
    periodBadge: {
      borderRadius: 999,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    periodBadgeText: {
      fontSize: 9,
      fontWeight: "900",
      writingDirection: dir,
    },

    builderCard: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      padding: 14,
      gap: 12,
      ...sh,
    },
    matiereTitle: {
      fontSize: 12.5,
      fontWeight: "900",
      textAlign: textEnd,
      writingDirection: dir,
    },
    matiereChipsWrap: {
      flexDirection: row,
      flexWrap: "wrap",
      gap: 8,
    },
    matiereChip: {
      flexDirection: row,
      alignItems: "center",
      gap: 6,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 13,
      borderWidth: 1.5,
    },
    matiereChipActive: {
      borderWidth: 2,
    },
    matiereChipText: {
      fontSize: 13,
      fontWeight: "800",
      writingDirection: dir,
    },
    matiereChipEmoji: {
      fontSize: 15,
      lineHeight: 20,
    },
    matiereChipImage: {
      width: 20,
      height: 20,
      borderRadius: 6,
    },
    matiereChipSkeleton: {
      width: 96,
      height: 38,
      borderRadius: 999,
      backgroundColor: `${palette.muted}1A`,
    },

    selectorSection: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      padding: 14,
      gap: 12,
      ...sh,
    },
    selectorTitleRow: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    selectorTitle: {
      fontSize: 13.5,
      fontWeight: "900",
      writingDirection: dir,
      textAlign: textEnd,
    },
    selectorSubtitle: {
      marginTop: 2,
      fontSize: 11.5,
      fontWeight: "600",
      writingDirection: dir,
      textAlign: textEnd,
      color: palette.muted,
    },
    selectorList: {
      gap: 10,
    },
    selectorCard: {
      flexDirection: row,
      alignItems: "center",
      gap: 12,
      borderRadius: 18,
      borderWidth: 1.5,
      padding: 12,
    },
    selectorCheck: {
      width: 24,
      height: 24,
      borderRadius: 999,
      borderWidth: 1.5,
      alignItems: "center",
      justifyContent: "center",
    },
    selectorAvatar: {
      width: 44,
      height: 44,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
    },
    selectorAvatarImage: {
      width: 44,
      height: 44,
      borderRadius: 999,
    },
    selectorAvatarText: { fontSize: 20 },
    selectorInfo: { flex: 1, gap: 3 },
    selectorName: {
      fontSize: 13.5,
      fontWeight: "800",
      writingDirection: dir,
      textAlign: textEnd,
    },
    selectorMeta: {
      flexDirection: row,
      alignItems: "center",
      gap: 6,
    },
    selectorMetaText: {
      fontSize: 11.5,
      fontWeight: "600",
      writingDirection: dir,
      color: palette.muted,
    },
    selectorRating: {
      fontSize: 11.5,
      fontWeight: "800",
      color: palette.gold,
    },
    selectorBookCover: {
      width: 44,
      height: 56,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    selectorBookCoverImage: {
      width: 44,
      height: 56,
      borderRadius: 8,
    },
    selectorBookTitle: {
      fontSize: 13,
      fontWeight: "800",
      writingDirection: dir,
      textAlign: textEnd,
    },
    selectorBookPrice: {
      fontSize: 12.5,
      fontWeight: "900",
      color: palette.primary,
    },
    selectorSkeleton: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      padding: 12,
      flexDirection: row,
      alignItems: "center",
      gap: 12,
    },
    selectorSkeletonCircle: {
      width: 44,
      height: 44,
      borderRadius: 999,
      backgroundColor: `${palette.muted}1A`,
    },
    selectorSkeletonBook: {
      width: 44,
      height: 56,
      borderRadius: 8,
      backgroundColor: `${palette.muted}1A`,
    },
    selectorSkeletonLines: { flex: 1, gap: 6 },
    selectorSkeletonLine: {
      height: 10,
      borderRadius: 999,
      backgroundColor: `${palette.muted}1A`,
    },
    selectorEmpty: {
      borderRadius: 18,
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: palette.border,
      backgroundColor: palette.surface,
      paddingVertical: 22,
      paddingHorizontal: 16,
      alignItems: "center",
      gap: 8,
    },
    selectorEmptyText: {
      fontSize: 12.5,
      fontWeight: "700",
      color: palette.muted,
      textAlign: "center",
      writingDirection: dir,
      lineHeight: 20,
    },

    dock: {
      position: "absolute",
      left: 16,
      right: 16,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      padding: 12,
      gap: 10,
      ...sh,
    },
    dockBubbles: {
      flexDirection: isRTL ? ("row-reverse" as const) : ("row" as const),
      flexWrap: "wrap",
      gap: 8,
    },
    dockBubble: {
      flexDirection: row,
      alignItems: "center",
      gap: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: `${palette.primary}55`,
      backgroundColor: `${palette.primary}14`,
      paddingLeft: 4,
      paddingTop: 4,
      paddingBottom: 4,
      paddingRight: 10,
    },
    dockBubbleAvatar: {
      width: 26,
      height: 26,
      borderRadius: 7,
      backgroundColor: palette.surface,
    },
    dockBubbleFallback: { fontSize: 14 },
    dockBubbleLabel: {
      fontSize: 11.5,
      fontWeight: "800",
      color: palette.text,
      writingDirection: dir,
      maxWidth: 130,
    },
    dockBubbleRemove: {
      width: 16,
      height: 16,
      borderRadius: 999,
      backgroundColor: "rgba(15,23,42,0.55)",
      alignItems: "center",
      justifyContent: "center",
    },
    dockFooter: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    dockPrice: { gap: 2, flexShrink: 1 },
    dockPriceValue: {
      fontSize: 16,
      fontWeight: "900",
      color: palette.primary,
      writingDirection: dir,
    },
    dockPeriodHint: {
      fontSize: 10.5,
      fontWeight: "600",
      color: palette.muted,
      writingDirection: dir,
    },
    dockCtaWrap: { flex: 1 },
    dockCta: {
      borderRadius: 999,
      overflow: "hidden",
    },
    dockCtaGradient: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 13,
      paddingHorizontal: 18,
      borderRadius: 999,
    },
    dockCtaText: {
      fontSize: 14,
      fontWeight: "900",
      color: "#FFFFFF",
      writingDirection: dir,
    },
    dockHelper: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingHorizontal: 8,
    },
    dockHelperText: {
      fontSize: 11,
      fontWeight: "700",
      color: palette.muted,
      textAlign: "center",
      writingDirection: dir,
    },

    stickyFooter: {
      paddingHorizontal: 16,
      paddingTop: 10,
      gap: 10,
      borderTopWidth: 1,
      borderTopColor: palette.border,
      backgroundColor: palette.bg,
    },
    summaryCard: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      padding: 14,
      gap: 8,
      ...sh,
    },
    summaryRow: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    summaryLabel: {
      flexShrink: 1,
      fontSize: 12,
      fontWeight: "700",
      color: palette.muted,
      writingDirection: dir,
      textAlign: textEnd,
    },
    summaryValue: {
      fontSize: 12.5,
      fontWeight: "800",
      color: palette.text,
      writingDirection: dir,
      textAlign: textEnd,
    },
    summaryDivider: {
      height: 1,
      backgroundColor: palette.border,
      marginVertical: 2,
    },
    summaryTotal: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    summaryTotalLabel: {
      fontSize: 14,
      fontWeight: "900",
      color: palette.text,
      writingDirection: dir,
      textAlign: textEnd,
    },
    summaryTotalValue: {
      fontSize: 18,
      fontWeight: "900",
      color: palette.primary,
    },
    summaryPeriodHint: {
      fontSize: 10.5,
      fontWeight: "600",
      color: palette.muted,
      writingDirection: dir,
      textAlign: textEnd,
    },

    ctaDisabled: { opacity: 0.5 },
    ctaHelperWrap: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingHorizontal: 8,
    },
    ctaHelperText: {
      fontSize: 11.5,
      fontWeight: "700",
      color: palette.muted,
      textAlign: "center",
      writingDirection: dir,
    },

    planCard: {
      borderRadius: 26,
      borderWidth: 1.5,
      padding: 18,
      width: "100%",
      ...sh,
    },
    planCardGrid: {
      flexBasis: "48%",
      flexGrow: 1,
      padding: 12,
      borderRadius: 20,
    },
    planCardGridFull: {
      flexBasis: "100%",
      flexGrow: 1,
    },
    cardSubscribeWrap: {
      marginTop: "auto",
      paddingTop: 14,
      borderRadius: 16,
      overflow: "hidden",
    },
    cardSubscribeBtn: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      height: 48,
      paddingHorizontal: 14,
    },
    cardSubscribeText: {
      color: "#FFFFFF",
      fontSize: 15,
      fontWeight: "800",
    },
    plansGrid: {
      flexDirection: row,
      flexWrap: "wrap",
      gap: 12,
    },
    plansList: {
      flexDirection: "column",
      gap: 12,
    },
    viewLayoutToggle: {
      flexDirection: row,
      borderRadius: 999,
      borderWidth: 1,
      padding: 3,
      gap: 2,
    },
    viewLayoutToggleHeader: {
      borderColor: "rgba(255,255,255,0.24)",
      backgroundColor: "rgba(255,255,255,0.10)",
    },
    viewLayoutOption: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 11,
      paddingVertical: 7,
      borderRadius: 999,
    },
    planCardPopular: {
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 10,
    },
    cardTopRow: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
      marginBottom: 12,
    },
    badgesRow: {
      flexDirection: row,
      alignItems: "center",
      gap: 8,
      flexWrap: "wrap",
    },
    popularPill: {
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
      flexDirection: row,
      alignItems: "center",
      gap: 6,
    },
    popularPillText: {
      color: "#FFFFFF",
      fontSize: 11,
      fontWeight: "900",
      writingDirection: dir,
    },
    typeBadge: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    typeBadgeText: {
      fontSize: 10,
      fontWeight: "800",
      writingDirection: dir,
    },
    planIconBadge: {
      width: 34,
      height: 34,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    planTitle: {
      fontSize: 20,
      fontWeight: "900",
      textAlign: textEnd,
      writingDirection: dir,
    },
    planTitleCompact: {
      fontSize: 15,
    },
    planDescription: {
      marginTop: 6,
      fontSize: 13,
      fontWeight: "600",
      textAlign: textEnd,
      writingDirection: dir,
      lineHeight: 22,
    },
    planDescriptionCompact: {
      marginTop: 3,
      fontSize: 11,
      lineHeight: 16,
    },

    priceHero: {
      marginTop: 16,
      borderRadius: 20,
      padding: 14,
      borderWidth: 1,
      gap: 6,
    },
    priceHeroCompact: {
      marginTop: 8,
      borderRadius: 14,
      padding: 8,
      gap: 3,
    },
    priceHeroTop: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
    },
    priceHeroBottom: {
      flexDirection: row,
      alignItems: "baseline",
      justifyContent: "space-between",
      gap: 10,
    },
    priceHintLabel: {
      fontSize: 11.5,
      fontWeight: "800",
      writingDirection: dir,
    },
    priceHintLabelCompact: {
      fontSize: 10,
    },
    discountBadge: {
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 3,
      backgroundColor: "rgba(245,166,35,0.16)",
    },
    discountBadgeText: {
      fontSize: 10,
      fontWeight: "900",
      color: "#FFFFFF",
    },
    oldPrice: {
      fontSize: 12,
      fontWeight: "700",
      textDecorationLine: "line-through",
    },
    priceValueRow: {
      flexDirection: row,
      alignItems: "baseline",
      gap: 4,
    },
    priceValue: {
      fontSize: 30,
      fontWeight: "900",
    },
    priceValueCompact: {
      fontSize: 22,
    },
    pricePerMonth: {
      fontSize: 12,
      fontWeight: "800",
    },
    pricePerMonthCompact: {
      fontSize: 10,
    },
    priceDivider: {
      height: 1,
      marginVertical: 6,
    },
    materialRow: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      paddingVertical: 6,
    },
    materialLabel: {
      flex: 1,
      fontSize: 12.5,
      fontWeight: "800",
      textAlign: textEnd,
      writingDirection: dir,
    },
    materialRowPrices: {
      flexDirection: row,
      alignItems: "center",
      gap: 8,
    },
    materialFinalPrice: {
      fontSize: 13.5,
      fontWeight: "900",
    },
    cardMaterialBlock: {
      marginTop: 14,
    },
    cardMaterialBlockCompact: {
      marginTop: 6,
    },
    cardMaterialBlockHeader: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    cardMaterialBlockHeaderCompact: {
      marginBottom: 6,
    },
    layoutToggleBtn: {
      flexDirection: row,
      alignItems: "center",
      gap: 5,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      marginBottom: 10,
    },
    layoutToggleBtnCompact: {
      paddingHorizontal: 7,
      paddingVertical: 4,
      marginBottom: 4,
    },
    layoutToggleLabel: {
      fontSize: 11.5,
      fontWeight: "800",
      writingDirection: dir,
    },
    cardMaterialGrid: {
      flexDirection: row,
      flexWrap: "wrap",
      gap: 8,
    },
    cardMaterialGridItem: {
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      borderRadius: 16,
      borderWidth: 1.5,
      paddingHorizontal: 8,
      paddingVertical: 12,
      minHeight: 96,
      flexBasis: "47%",
    },
    cardMaterialGridItemCompact: {
      minHeight: 52,
      borderRadius: 12,
      gap: 2,
      paddingHorizontal: 3,
      paddingVertical: 6,
    },
    cardMaterialGridItemFull: {
      flexBasis: "100%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 10,
      minHeight: 58,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    cardMaterialGridItemActive: {
      borderWidth: 2,
    },
    cardTileCheck: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 20,
      height: 20,
      borderRadius: 6,
      borderWidth: 1.5,
      alignItems: "center",
      justifyContent: "center",
    },
    cardMaterialTileEmoji: {
      fontSize: 24,
      lineHeight: 28,
    },
    cardMaterialTileEmojiCompact: {
      fontSize: 17,
      lineHeight: 20,
    },
    cardMaterialLabel: {
      fontSize: 12.5,
      fontWeight: "800",
      textAlign: "center",
      writingDirection: dir,
    },
    cardMaterialLabelCompact: {
      fontSize: 10.5,
    },
    cardMaterialPrice: {
      fontSize: 12.5,
      fontWeight: "900",
    },
    cardMaterialPriceCompact: {
      fontSize: 10,
    },

    sectionLabel: {
      fontSize: 12.5,
      fontWeight: "900",
      textAlign: textEnd,
      writingDirection: dir,
      marginBottom: 10,
      letterSpacing: 0.2,
    },

    featuresBlock: {
      marginTop: 18,
    },
    featuresBlockCompact: {
      marginTop: 8,
    },
    featureRow: {
      flexDirection: row,
      alignItems: "flex-start",
      gap: 10,
      marginBottom: 10,
    },
    featureRowCompact: {
      gap: 8,
      marginBottom: 6,
    },
    featureIconWrap: {
      width: 26,
      height: 26,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 0,
    },
    featureTexts: {
      flex: 1,
      alignItems: alignEnd,
    },
    featureTitle: {
      fontSize: 13,
      fontWeight: "800",
      textAlign: textEnd,
      writingDirection: dir,
    },
    featureTitleCompact: {
      fontSize: 10.5,
    },
    featureDescription: {
      marginTop: 2,
      fontSize: 11.5,
      fontWeight: "600",
      textAlign: textEnd,
      writingDirection: dir,
      lineHeight: 18,
    },
    featureDescriptionCompact: {
      fontSize: 9,
      lineHeight: 12,
    },

    accessibleWrap: {
      marginTop: 18,
    },
    accessibleChipsRow: {
      flexDirection: row,
      flexWrap: "wrap",
      gap: 8,
    },
    accessibleChip: {
      maxWidth: W - 80,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
    },
    accessibleChipText: {
      fontSize: 11,
      fontWeight: "800",
      writingDirection: dir,
      textAlign: textEnd,
    },

    ctaBtn: {
      marginTop: 18,
      borderRadius: 999,
      overflow: "hidden",
      ...sh,
    },
    ctaGradient: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 15,
      borderRadius: 999,
    },
    ctaText: {
      fontSize: 15,
      fontWeight: "900",
      color: "#FFFFFF",
      writingDirection: dir,
    },

    guaranteeWrap: {
      flexDirection: row,
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
      paddingVertical: 12,
      borderRadius: 999,
    },
    guaranteeText: {
      fontSize: 12,
      fontWeight: "800",
      writingDirection: dir,
    },
  });
}

export type PlansScreenStyles = ReturnType<typeof createPlansStyles>;
