export const ConfigEnv = {
  API_ENDPOINT: process.env.EXPO_PUBLIC_API_ENDPOINT,
  HASH_KEY: process.env.EXPO_PUBLIC_HASH_KEY,

  MEDIA_BASE_URL: process.env.EXPO_PUBLIC_MEDIA_BASE_URL,

  DEFAULT_LOCALE: process.env.EXPO_PUBLIC_DEFAULT_LOCALE,
  SUPPORTED_LOCALES: process.env.EXPO_PUBLIC_SUPPORTED_LOCALES,

  MEDIA_S3_BUCKET: process.env.EXPO_PUBLIC_MEDIA_S3_BUCKET,
  S3_BUCKET_URL: process.env.EXPO_PUBLIC_S3_BUCKET_URL,
  PUSHER_KEY: process.env.EXPO_PUBLIC_PUSHER_KEY,
  PUSHER_CLUSTER: process.env.EXPO_PUBLIC_PUSHER_CLUSTER,
  BORADCASTING_URL: process.env.EXPO_PUBLIC_API_BROEADCATING_URL,
} as const