export const PATHS = {
  AUTH: {
    ROOT: "Auth",
    WELCOME: "Welcome",
    SIGN_IN: "SignIn",
    SIGN_UP: "SignUp",
    FORGET_PASSWORD: "ForgetPassword",
    VERIFICATION: "Verification",
    RESET_PASSWORD: "ResetPassword",
  },

  ONBOARDING: {
    ROOT: "Onboarding",
    ADD_KIDS: "AddKids",
  },

  APP: {
    ROOT: "App",
    TABS: "HomeTabs",
    SETTINGS: "Settings",
    PROFILE_PARENT: "ProfileParent",
    ADD_KIDS: "AddKids",
    KIDS_LIST: "KidsList",
    TEACHER_PROFILE: "TeacherProfile",
    PARENT_DASHBOARD: "ParentDashboard",
    COURSE_CHAPTERS: "CourseChapters",
    FAVORITE_COURSES: "FavoriteCourses",
    BOOKS_FILE: "BooksFile",
    BOOKS: "Books",
    VIDEO: "Video",
    NOTIFICATIONS: "Notifications",
    MATERIAL_HUB: "MaterialHub",
    MEETING_DETAILS: "Meeting_details",
    RESERVED_MEETINGS: "ReservedMeetings",
    JOIN_SESSION: "JoinSession",
    PLANS: "Plans",
    DETAIL_PLAN_MEETING: "DetailPlanMetting",
    TRAILERS: "Trailer",

    // Static design showcase screens
    START_LEARNING: "StartLearning",
    PROGRESS_TODAY: "ProgressToday",
    EDU_HOME: "EduHome",
    STUDY_GUIDE: "StudyGuide",
    STUDY_CRAFT: "StudyCraft",
    AI_OWL: "AIOwl",
    SCAN_QR_CODE: "ScanQRCode",
    LEARN_CALENDAR: "LearnCalendar",
    CUSTOMIZE_AVATAR: "CustomizeAvatar",
    TOPUP: "Topup",
  },

  TABS: {
    BOOKS: "Books",
    COURSES: "Courses",
    MEETINGS: "Meetings",
    RESERVED_MEETINGS: "ReservedMeetings",
    SETTINGS: "Settings",
    HOME: "Home",
    PLANS: "Plans",
    SUBSCRIPTION: "Subscription",
    STUDY_GUIDE: "StudyGuide",
    MEETING_VIEW: "MeetingView",
    START_LEARNING: "StartLearning",
    PROGRESS_TODAY: "ProgressToday",
    EDU_HOME: "EduHome",
    STUDY_CRAFT: "StudyCraft",
    AI_OWL: "AIOwl",
    SCAN_QR_CODE: "ScanQRCode",
    LEARN_CALENDAR: "LearnCalendar",
  },
} as const;